apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: myangular
  name: myangular
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: myangular
    spec:
      containers:
      - image: houcemserver/angular
        name: myangular
        ports:
        - name: myangular
          containerPort: 2222    
          
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: myangular
  name: myangular
spec:
  type: NodePort
  ports:
    - port: 2222
      targetPort: 2222
  selector:
    name: myangular
